### ISSUE TITLE
Configure Build on Docker Hub

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [nlamirault/speedtest_exporter#12]
@nlamirault, it would be great to have this repository configured to automatically build images on Docker Hub. Currently PRs must be merged here and then @tnwhitwell must merge it too on his fork to have an available Docker image on https://hub.docker.com/r/tnwhitwell/speedtest_exporter.

**Comment by tnwhitwell** [comment]
In the meantime, I’ll get my fork updated this AM

**Comment by tnwhitwell** [comment]
> In the meantime, I’ll get my fork updated this AM

Done - it's building now. I'll try to fudge something together to get it to autobuild without too much pain.

**Comment by tnwhitwell** [comment]
Autobuild is now fudged - ~30m after each commit to this repo, my pipeline will pick up the change and will build a new docker image. Badges in [tnwhitwell/speedtest_exporter](https://github.com/tnwhitwell/speedtest_exporter) will be updated with the latest image version after it's been scanned by microbadger.
