### ISSUE TITLE
Allow server IDs to be configurable

### ISSUE THREAD

**Issue by madAndroid** [nlamirault/speedtest_exporter#18]
It would be awesome if the exporter could allow a set of server IDs to be configured - currently the list of "closest" servers is chosen, but having this be configurable would mean being able to test speeds to multiple different locations, allowing testing of transatlantic links etc

**Comment by dfiore1230** [comment]
2nd. 

It does seem like its available to set manually, but appears you have to rebuild the docker container if using docker. Line 19 of prometheus_speedtest.py
