### ISSUE TITLE
Replace zpeters/speedtest

### ISSUE THREAD

**Issue by nlamirault** [nlamirault/speedtest_exporter#3]
According to https://github.com/zpeters/speedtest : 

```
Notice

I no longer have time to actively develop this code. There are currently multiple speed issues that i don't have time to track down. It appears that Ookla is working on a beta site that will completely change the interface which woudl require a pretty much complete rewrite. For the moment i will accept and patches but i wont be actively doing any development.
```
Other implementation : 
* https://github.com/showwin/speedtest-go

**Comment by ipsecguy** [comment]
Hi,

seems to be slightly better when I choose the server manually, especially the latency.

Target Server: [1746]    21.10km Frankfurt (Germany) by Vodafone DE
Latency: 6.083165ms
Download Test: ................
Upload Test: ................

Download: 83.38 Mbit/s
Upload: 35.44 Mbit/s

I have to test again in a low traffic time of day, i keep you posted.

Andreas

**Comment by prologic** [comment]
I *think* you should consider replacing this dependency :)

```
prologic@Jamess-MacBook
Sat Apr 28 23:27:38
~/go/src/github.com/nlamirault/speedtest_exporter
 (master) 1
$ make init
[speedtest_exporter] Install requirements
package golang.org/x/tools/cmd/oracle: cannot find package "golang.org/x/tools/cmd/oracle" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/golang.org/x/tools/cmd/oracle (from $GOROOT)
	/Users/prologic/go/src/golang.org/x/tools/cmd/oracle (from $GOPATH)
make: *** [init] Error 1
```

I'm not sure the master branch builds :/
